### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by aidanheerdegen** [ACCESS-NRI/ACCESS-ESM1.5#10]
README is minimal. Needs to be updated. See https://github.com/ACCESS-NRI/ACCESS-OM2 for an example.

**Comment by dougiesquire** [comment]
Stolen from https://github.com/ACCESS-NRI/ACCESS-ESM1.6/issues/3

> Should also include the requirements in order to compile/develop the code, as it requires being added to some private repos.

**Comment by dougiesquire** [comment]
Drafting requirements for users to be added to the private repos:

- A UKMO MOSRS account
- Member of Gadi `ki32_mosrs` project (or `access`) - @penguian , @aidanheerdegen to confirm

**Comment by dougiesquire** [comment]
Copied from Slack:

@penguian 
Neither UM7 nor GCOM4 should need `ki32_mosrs` since they are supposed to be independent of the MOSRS repository. I think `access` is needed, but would have to check.


@ccarouge 
They might be independent of MOSRS but do we want to ask all users of UM and other UKMO codes to have a MOSRS account so UKMO can contact them, take them into account in their reporting numbers etc. ?

@aidanheerdegen 
We made a decision to use `ki32_mosrs` membership as a gate-keeping mechanism on gadi, but that does put a pretty large burden on short-term users, e.g. students.


@ccarouge 
large burden? How so?


@aidanheerdegen 
Signing up for a MOSRS account requires Martin and other people to ok it all right? I’m thinking of those students of Julie’s that might only run the model for a very short period of time.


@ccarouge 
Could we have a lighter set of requirements for training and courses attendees vs “proper” users? I’m not certain how to manage that though…

**Comment by aidanheerdegen** [comment]
Snitch

**Comment by aidanheerdegen** [comment]
On a Friday afternoon. Good luck with that.

**Comment by ccarouge** [comment]
So I guess @dougiesquire is trying to get @aidanheerdegen and I to agree on what to do. If a MOSRS account is seen as too heavy a requirement that's fine with me.

But we still have the following problem: what is the criteria to add someone to the private repositories? Most users might not need access to the code repo and just use the pre-compiled module, but we will always have people who need access. How do we know that? Do we need to keep track of any information for this?
